apiVersion: v1
kind: Secret
metadata:
  name: users-import-secrets
  namespace: users-import
type: Opaque
stringData:
  MONGO_USERNAME: admin
  MONGO_PASSWORD: admin123
  MONGO_AUTH_SOURCE: admin

  RABBITMQ_USER: appuser
  RABBITMQ_PASSWORD: apppass
  RABBITMQ_URL: amqp://appuser:apppass@rabbitmq:5672

  REDIS_PASSWORD: redis123
  REDIS_URL: redis://:redis123@redis:6379

  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin123


