apiVersion: v1
kind: ConfigMap
metadata:
  name: users-import-app-config
  namespace: users-import
data:
  PORT: "3000"
  API_PREFIX: ""
  TRUST_PROXY: "false"
  CORS_ORIGINS: ""

  MONGO_URI: "mongodb://mongo:27017/users_db"

  RABBITMQ_QUEUE: "import-users.queue"
  RABBITMQ_PREFETCH: "20"
  REDIS_PORT: "6379"

  SWAGGER_ENABLED: "true"
  SWAGGER_PATH: "docs"
  SWAGGER_TITLE: "Users Import API"
  SWAGGER_DESCRIPTION: "Users CRUD + async import API"
  SWAGGER_VERSION: "1.0.0"


