{
 "title": "Users Import API - Runtime",
 "tags": [
  "users-import",
  "nestjs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Resident Memory (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{app=\"users-import-api\"})"
    }
   ]
  },
  {
   "title": "CPU Usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{app=\"users-import-api\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_http_requests_total{app=\"users-import-api\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Latency p95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_http_request_duration_seconds_bucket{app=\"users-import-api\"}[5m])) by (le))"
    }
   ]
  }
 ]
}