export const TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  IMPORT_JOB_REPOSITORY: 'IMPORT_JOB_REPOSITORY',
  IMPORT_JOB_ITEM_REPOSITORY: 'IMPORT_JOB_ITEM_REPOSITORY',
  CACHE_PORT: 'CACHE_PORT',
  IMPORT_PUBLISHER_PORT: 'IMPORT_PUBLISHER_PORT',
} as const;
